root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  full_bin = "./tmp/main serve -p 8085"
  delay = 1000
  exclude_dir = ["build", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  stop_on_error = true
  log = "build-errors.log"
  send_interrupt = true
  kill_delay = "5s"

[color]
  app = "magenta"
  build = "yellow"
  main = "cyan"
  runner = "green"
  watcher = "blue"

[log]
  time = true
  main_only = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true
