global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Rule files for alerting
rule_files:
  - "rules/crawler_alerts.yml"

scrape_configs:
  # Pushgateway scraping configuration
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
    metrics_path: /metrics
    scrape_interval: 5s

  # Health monitoring for Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Your existing configs...
  - job_name: 'goprowl'
    static_configs:
      - targets: ['pushgateway:9091']
    metric_relabel_configs:
      - source_labels: [crawler_id]
        target_label: crawler
        regex: '(.*)'
        replacement: '${1}'
